# Generated by Django 5.0.7 on 2024-08-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscrapeevent',
            name='jumia_product',
        ),
        migrations.DeleteModel(
            name='JumiaProduct',
        ),
        migrations.DeleteModel(
            name='ProductScrapeEvent',
        ),
    ]
