# Generated by Django 5.0.7 on 2024-08-13 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeBaseURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://www.jumia.co.ke/', max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JumiaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=450, unique=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=450, null=True)),
                ('image_url', models.CharField(blank=True, max_length=450, null=True)),
                ('url', models.CharField(blank=True, max_length=350, null=True)),
                ('current_price', models.FloatField(default=0.0)),
                ('old_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount_percent', models.CharField(blank=True, max_length=155, null=True)),
                ('ratings', models.CharField(blank=True, max_length=155, null=True)),
                ('express_shipping', models.BooleanField(default=False)),
                ('sponsored', models.BooleanField(default=False)),
                ('extra_description', models.CharField(blank=True, max_length=450, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jumia.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductScrapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(default=0.0)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jumia_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_events', to='jumia.jumiaproduct')),
            ],
        ),
    ]
