# Generated by Django 5.0.8 on 2024-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumia', '0003_userproductsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumiaproduct',
            name='product_name',
            field=models.CharField(max_length=450),
        ),
    ]
